"""workflow update

Revision ID: 388f274b79b9
Revises: 5ae9794ca0ad
Create Date: 2026-04-30 16:05:44.597364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '388f274b79b9'
down_revision: Union[str, Sequence[str], None] = '5ae9794ca0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['updated_by'], ['id'])
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('admin', 'manager', 'employee', 'user', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'manager', 'employee', 'user', name='userrole'),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'updated_by')
    # ### end Alembic commands ###
